### ISSUE TITLE
External token exchange

### ISSUE THREAD

**Issue by z0mb1ek** [BenjaminFavre/keycloak-apple-social-identity-provider#13]
Hi. Firstly big thanks for your work! I try this provider and it works fine for web auth. Now I want to add native ios authorization and make external token change from apple token to keycloak token. I can do this if I set OpenID Connect v1.0 provider and set this fields: 
<img width="887" alt="Screenshot 2021-03-19 at 18 45 01" src="https://user-images.githubusercontent.com/1172005/111806619-38fd2500-88e3-11eb-8a36-a1e79990a2ff.png">

How can I add this option to this provider?

**Comment by z0mb1ek** [comment]
Finally make it myself with aud of native client support

**Comment by Baer05** [comment]
@z0mb1ek please can you show the setting of the identity-provider and youre post configuration for the api call?
