### ISSUE TITLE
Failed to make identity provider oauth callback

### ISSUE THREAD

**Issue by MatteoGioioso** [BenjaminFavre/keycloak-apple-social-identity-provider#16]
We have setup this provider, however we are having this error:

```
Failed to make identity provider oauth callback: java.lang.IllegalArgumentException: Illegal base64 character 20
```

The provider is visible in the list: 
![image](https://user-images.githubusercontent.com/43592430/131332795-c91174b2-0ca9-4d2c-9225-0fefc0c79a8a.png)

Thanks

**Comment by MatteoGioioso** [comment]
My bad, it was probably some trailing new line with the client secret

**Comment by Karthik1152** [comment]
my bad i am still getting above issue. but not yet fixed
can anyone help me???

**Comment by kmejri1** [comment]
Hello, 

Did you find the solution for this problem please ? I have the same now and this is totally blocking

Please help
