### ISSUE TITLE
How to add Apple logo to the identity provider?

### ISSUE THREAD

**Issue by kristianbendren** [BenjaminFavre/keycloak-apple-social-identity-provider#17]
Hi,
i got this to work but have no Apple logo. Is this possible to add somehow?

**Comment by BenjaminFavre** [comment]
Hi,
You’ll have to extend the theme you use to add the asset, I can’t do this from the provider.
Note that Apple is very restrictive on the way you display their logo, you will have to use the **exact** button image you’ll find on their guidelines. Otherwise, you app submission to the appstore will be rejected.

**Comment by kristianbendren** [comment]
Hi Bejamin,
can you guide us a bit more where in the theme we should add it.
We have seperate themes today but just need guidance on this.

The identity Provider is named apple in keycloak


I guess we need to add some CSS and that we can figure out but we dont know where to add it exactly in the theme. 

Thanks!

**Comment by stefanwendelmann** [comment]
Rewrite this from apple to appstore in the class and it works.
I did not figure out how exactly it outputs apple here but this is maybe a begin:

https://github.com/smcllns/css-social-buttons/blob/master/src/appstore.svg

![image](https://user-images.githubusercontent.com/3920790/140902869-dac8f1b7-dc05-408c-ac9e-99833f400468.png)

![image](https://user-images.githubusercontent.com/3920790/140903274-5f088c59-fcef-4359-b172-3dc06f79f7ae.png)

**Comment by kristianbendren** [comment]
Thx there was already a predefined css class so i just added it and it works. Thx!
