### ISSUE TITLE
Advertise extension on keycloak.org

### ISSUE THREAD

**Issue by stianst** [BenjaminFavre/keycloak-apple-social-identity-provider#29]
If there is interest in it, it would be great to see this extension listed on https://www.keycloak.org/extensions.html

A simple PR to https://github.com/keycloak/keycloak-web/tree/main/extensions is all that is needed to do that. I would prefer the PR comes from one of the maintainers of this repository though.

**Comment by klausbetz** [comment]
You may want to consider this [extension](https://github.com/klausbetz/apple-identity-provider-keycloak) as it also supports `token exchange` (exchanging Apple authorization codes for Keycloak `access_token/refresh_token`), which is interesting for native `Sign in with Apple` on iOS/iPad OS devices.

**Comment by stianst** [comment]
> klausbetz

https://github.com/klausbetz/apple-identity-provider-keycloak/issues/9
