### ISSUE TITLE
After installing in KeyCloak Apple does not appear as provider

### ISSUE THREAD

**Issue by gezamiklo** [BenjaminFavre/keycloak-apple-social-identity-provider#8]
The jboss-deployment-structure.xml did not include all the dependencies. The following had to be added.
```
<module name="javax.ws.rs.api" export="true"/>
```

Still it does not appear. What else should be done? Should any configuration files be updated?

**Comment by SalahAdDin** [comment]
@gezamiklo [here](https://github.com/BenjaminFavre/keycloak-apple-social-identity-provider/issues/10) it says it appears on, but it does not work.

**Comment by gezamiklo** [comment]
After some research I've found that the old JAVA version on the server caused the problem. At least JAVA 11 has to be installed.

**Comment by SalahAdDin** [comment]
@gezamiklo Are you using a local machine or a **Docker** container?

**Comment by gezamiklo** [comment]
@SalahAdDin It runs in a docker container. I cannot tell much about that. Our sysadmin-s manage the backends. I just tried to load the provider with the auto deployment method.

Copied the jar to standalone/deployments. As a new file having .deployed extension appeared, I could add new Apple provider in my realm.

**Comment by SalahAdDin** [comment]
@gezamiklo @BenjaminFavre [said](https://github.com/BenjaminFavre/keycloak-apple-social-identity-provider/issues/7#issuecomment-775102351) putting the `jar` file on the  _deployments_ folder was enough.
